#!/bin/sh

page_count=`pdf_page_count "$1"`
len=`pdf_util_len "$1"`
for i in `seq -f "%0${len}g" 1 $page_count`; do
    yes | gs -dBATCH -sOutputFile="${2-page}${i}.pdf" -dFirstPage=${i} -dLastPage=${i} -sDEVICE=pdfwrite "$1" >& /dev/null
done
